### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'terraform'

### ISSUE THREAD

**Issue by guptakvgaurav** [localstack/terraform-local#10]
While localstack worked well with awslocal for me. but switching from awslocal to tflocal gave me the following error.

```
terraform-event-system git:(main) tflocal --help                                               
Traceback (most recent call last):
  File "/home/gaurav.gupta/miniconda3/envs/venv_localstack_poc/bin/tflocal", line 191, in <module>
    main()
  File "/home/gaurav.gupta/miniconda3/envs/venv_localstack_poc/bin/tflocal", line 185, in main
    run_tf_subprocess(cmd, env)
  File "/home/gaurav.gupta/miniconda3/envs/venv_localstack_poc/bin/tflocal", line 163, in run_tf_subprocess
    PROCESS = subprocess.Popen(
  File "/home/gaurav.gupta/miniconda3/envs/venv_localstack_poc/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/gaurav.gupta/miniconda3/envs/venv_localstack_poc/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'terraform'

```

Environment detail:

- OS: Ubuntu 20.04
- Using conda environment

**Comment by buiducnhat** [comment]
I got the same error like you, how did you solve this?

**Comment by alexrashed** [comment]
@buiducnhat: This error indicates that you don't have `terraform` installed on your machine (`tflocal` actually is just a small wrapper around `terraform`). So please make sure that you have `terraform` installed correctly, and if you are still running in to issues, please create a new issue (comments on closed issues are hard to track / not very visible).

**Comment by buiducnhat** [comment]
> @buiducnhat: This error indicates that you don't have `terraform` installed on your machine (`tflocal` actually is just a small wrapper around `terraform`). So please make sure that you have `terraform` installed correctly, and if you are still running in to issues, please create a new issue (comments on closed issues are hard to track / not very visible).

Thanks so much!
And I have a problem when using `terraform` without `terraform-local`, do you know the problem?
```
│ Error: creating Amazon S3 (Simple Storage) Bucket (my-bucket): RequestError: send request failed
│ caused by: Put "http://my-bucket.localhost:4566/": dial tcp: lookup my-bucket.localhost: no such host
│ 
│   with aws_s3_bucket.my_bucket,
│   on main.tf line 33, in resource "aws_s3_bucket" "my_bucket":
│   33: resource "aws_s3_bucket" "my_bucket" {
```
This is `main.tf` file:
```terraform
provider "aws" {
  access_key                  = "test"
  region                      = "us-east-1"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    route53        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    ec2            = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
  }
}

resource "aws_s3_bucket" "my_bucket" {
  bucket = "my-bucket"
}
```

**Comment by alexrashed** [comment]
If you are not using `tflocal`, please follow our configuration guide in our docs: https://docs.localstack.cloud/user-guide/integrations/terraform.
It also contains a minimum working config here: https://docs.localstack.cloud/user-guide/integrations/terraform/#final-configuration

**Comment by buiducnhat** [comment]
> If you are not using `tflocal`, please follow our configuration guide in our docs: https://docs.localstack.cloud/user-guide/integrations/terraform. It also contains a minimum working config here: https://docs.localstack.cloud/user-guide/integrations/terraform/#final-configuration
> 
> This should solve your issues (hopefully). Otherwise, please create a new issue.

Thanks, after add this config: `s3_use_path_style = true`, it works
