### ISSUE TITLE
Override aliased providers

### ISSUE THREAD

**Issue by ricoli** [localstack/terraform-local#11]
# Summary
Currently `tflocal` is only overriding the default AWS provider, but it is common to have more than one AWS provider defined per terraform state, using [aliased providers](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations). This is most commonly used when mixing resources in different AWS regions in the same terraform state. It would be great if tflocal could also override these aliased providers.

# Current behaviour
Given the following providers:
```
provider "aws" {
  region = eu-west-2
}

provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
}
```
And no valid (real) AWS credentials configured, this is the output when running terraform against localstack using `tflocal`:
```
╷
│ Error: configuring Terraform AWS Provider: error validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 99a8111f-87b0-49e2-8794-fb08b80bdaac, api error InvalidClientTokenId: The security token included in the request is invalid.
│ 
│   with provider["registry.terraform.io/hashicorp/aws"].us_east_1,
│   on aliased-providers.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
╵
```
 This is of course because the aliased provider was not overriden and therefore the real AWS APIs were used instead of localstack.

# Proposed implementation
This is where it gets tricky: Terraform enforces aliased providers uniqueness so we can't simply use the same approach that `tflocal` currently has of creating a new file with the overridden (default) provider. One solution could be to actually modify the aliased providers defined to point to localstack, making use of https://pypi.org/project/python-hcl2/ for that. Such an implementation would also require resetting the providers to the previous state upon any errors or at the end of the execution - no small change!

# Workarounds
One possible workaround is to isolate the aliased providers in a separate file (i.e. aliased-providers.tf) and have a new file with the overridden providers (i.e. aliased-providers-override.tf.disabled) that terraform won't normally pick up. Then it's a matter of switching around the file extensions of said files before executing `tflocal` and restore the initial file names after the `tflocal` execution. Example using a shell script wrapper:
```
#!/usr/bin/env bash
set -e

disable_aliased_providers_override() {
  [[ -f aliased-providers-override.tf ]] && mv aliased-providers-override.tf aliased-providers-override.tf.disabled;
  [[ -f aliased-providers.tf.disabled ]] && mv aliased-providers.tf.disabled aliased-providers.tf;
}

trap "disable_aliased_providers_override" ERR
mv aliased-providers-override.tf.disabled aliased-providers-override.tf
mv aliased-providers.tf aliased-providers.tf.disabled
tflocal <terraform command goes here>
mv aliased-providers-override.tf aliased-providers-override.tf.disabled
mv aliased-providers.tf.disabled aliased-providers.tf
```
And this is what an overridden aliased provider would look like:
```
provider "aws" {
  alias                       = "us_east_1"
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  region                      = "us-east-1"
  endpoints {
    acm        = "http://localhost:4566"
    cloudfront = "http://localhost:4566"
    <any other AWS services that will be using this provider...>
  }
}
```

**Comment by whummer** [comment]
Thanks for reporting @ricoli , this is a great proposal, and we should definitely look into supporting this use case. 👍 

I'm wondering if we can find an even easier/user-friendly way to support this - for example there exist some HCL parsers in Python out there (e.g., [this](https://github.com/virtuald/pyhcl), or [this](https://github.com/amplify-education/python-hcl2) one), which may come in handy here.. 🤔 

Would you have capacity to help spike out a first implementation? We cannot commit to a timeline for this feature from LocalStack side, but definitely happy to help shepherd a contribution if you're up for it..! 🙌

**Comment by whummer** [comment]
Hi again @ricoli , quick update. We have now added initial support for provider aliases. Can you please give it a try with the latest version of `tflocal` (`0.7`).

**Comment by ricoli** [comment]
> Hi again @ricoli , quick update. We have now added initial support for provider aliases. Can you please give it a try with the latest version of `tflocal` (`terraform-local>=0.7`)? Please keep us posted on how it goes.. Thanks!

hi @whummer - I have tested it and it worked great, no more need for workarounds! Thanks!
