### ISSUE TITLE
tflocal apply hangs with -chdir option

### ISSUE THREAD

**Issue by zopyx** [localstack/terraform-local#2]
- Localstack 1.0.1
- Terraform 1.2.5 
- Ubuntu latest

I have a simple example TF configuration for testing and playing in a subfolder `terraform`.
Running `terraform init` and `terraform apply` works fine against Localstack

Running both commands from the parent directoy with option `-chdir=terraform` works for `terraform -chdir=terraform init` works. However, the `terraform -chdir=terraform apply` just hangs.

**Comment by whummer** [comment]
Thanks for reporting @zopyx , and apologies for the long delay. We have now pushed a small update that should (hopefully) get this issue resolved. 

Can you please upgrade to the latest version and give it another try:
```
pip install --upgrade 'terraform-local>=0.3'
```

Please let us know if the problem persists.. Thanks!
