### ISSUE TITLE
tflocal apply: An argument is not expected here

### ISSUE THREAD

**Issue by fasterinnerlooper** [localstack/terraform-local#24]
Hi all,

I'm receiving the following error message when I run `tflocal apply` inside my terraform directory:

```Error: Unsupported argument
│ 
│   on localstack_providers_override.tf line 57, in provider "aws":
│   57: keyspaces = "http://localhost:4566"
│ 
│ An argument named "keyspaces" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on localstack_providers_override.tf line 69, in provider "aws":
│   69: opensearch = "http://localhost:4566"
│ 
│ An argument named "opensearch" is not expected here.
```

I made sure that I have the latest versions of tflocal and localstack-client installed via pip, but I'm still getting the above error.

**Comment by steffyP** [comment]
Hi @sjetha,

thanks for reporting. Please be aware that `keyspaces` is currently not supported in LocalStack.
We recently detected some issues with the latest aws-provider by terraform (`v5.9.0`) which might also cause the issues you are describing.

Could you try to pin the version you are using and let us know if this resolves the issue for you? E.g. 
```
provider "aws" {
  region = "us-east-1"
  version = "<= 5.8.0"
}
```

**Comment by sjetha** [comment]
Hi @steffyP. I've double-checked that I'm using the latest version of terraform-local, and I'm still getting the error. Do I need to upgrade the version of terraform I'm using? I'm currently on version 1.5.3.

**Comment by steffyP** [comment]
Hey @sjetha, 

terraform 1.5.3 seems to be latest release already. Are you using the latest aws-provider as well (e.g. `5.9.0`)?
Else could you please provide a reproducible sample? 🙏

**Comment by pedrovitorlima** [comment]
I had the same issue and I think I solved the problem. I'm using terraform-local 0.12, terraform 1.5.3. 

1. Set the aws provider as ~>5.0 
```
required_providers {
        aws = {
            source = "hashicorp/aws"
            version = "~>5.0"
        }
    }
```

3. Do `tflocal init -upgrade
`

**Comment by lakkeger** [comment]
I was unable to recreate the same scenario anymore with v0.15. Closing the issue.
