### ISSUE TITLE
Best practice for local deployment and remote deployment with same IAC?

### ISSUE THREAD

**Issue by hjfitz** [localstack/terraform-local#28]
I'm working with Terraform locally and it's nice - nothing to complain about.

I want to use tflocal to test my infra out locally, and once I'm happy use that same code to deploy to AWS.

The challenge here is, I'm setting an environment variable with my DynamoDB host. It should ideally change to whatever the AWS one is when deploying remote, and local when deploying local. Is there any flag/variable that I can check, or am I stuck setting an input variable with something like `TF_VAR_is_local_deployment=1`?

**Comment by lakkeger** [comment]
Hi @hjfitz,
Thank you for your patience.

Unfortunately `tflocal` is not providing any options for such cases.
If I understand your issue right you have 2 options here to make your CI aware of it's environment:
- you either set the variable depending what binary you are using to run terraform
- or ie in gitlab/github you have the option to define variables by environments, so you don't need to check anything just use the variable with the right value on your branch

**Comment by lakkeger** [comment]
Closing the "issue" as it's only loosely terraform-local related.
