### ISSUE TITLE
tflocal - An argument named "meteringmarketplace" is not expected here.

### ISSUE THREAD

**Issue by cam71101** [localstack/terraform-local#3]
### **Is there an existing issue for this?**
 I have searched the existing issues
### **Current Behavior**
I try to use localstack with terraform, I followed your official documentation https://docs.localstack.cloud/integrations/terraform/.
The infrastructure terraform code has no relation to meteringmarketplace. 
I used tflocal in order to deploy my infra on localstack , but always I got the error bellow:

│ Error: Unsupported argument
│ 
│   on localstack_providers_override.tf line 67, in provider "aws":
│   67: meteringmarketplace = "http://localhost:4566"
│ 
│ An argument named "meteringmarketplace" is not expected here.
Expected Behavior
No response

### **How are you starting LocalStack?**
With the localstack script

### **Steps To Reproduce**
**How are you starting localstack (e.g., bin/localstack command, arguments, or docker-compose.yml)**
localstack start
**Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)**
tflocal init
tflocal plan
Environment
- OS: Big Sur 11.6.7
- LocalStack: latest

**Comment by whummer** [comment]
Thanks for reporting @cam71101  - this should be fixed in the meantime.

Can you please try installing the latest version and give it another try:
```
pip install --upgrade 'terraform-local>=0.4'
```
Please let us know if the problem persists.. Thanks!
