### ISSUE TITLE
Warning: AWS account ID not found for provider

### ISSUE THREAD

**Issue by kbret1** [localstack/terraform-local#36]
We are using 
Terraform version 1.6.2
terraform-local  version 0.16.0

We are receiving this error message.
Warning: AWS account ID not found for provider
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on _init.tf line 12, in provider "aws":
│   12: provider "aws" {
│ 
│ See https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_requesting_account_id for implications.

provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "us-east-1"
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints { ...
  
We specify skip_requesting_account_id but it is not in the localstack_providers_override.tf 

provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
   region = "us-east-1"
 endpoints { ....
  ......

**Comment by lakkeger** [comment]
Hi @kbret1,
Thank you for reaching out.
Your warning message is related to this line in your `provider` config:
`skip_requesting_account_id = true`
Terraform merges together your code blocks and the contents of the `*_override.tf` file which results in a final in-memory terraform code similar to this:
```
provider "aws" {
  access_key = "test"
  secret_key = "test"
  region = "us-east-1"
  s3_use_path_style = true
  skip_credentials_validation = true
  skip_metadata_api_check = true
  skip_requesting_account_id = true
  endpoints { ....
```
If you remove the line mentioned in the warning message from your provider configuration, the message is gone for good as terraform will be able to request the account ID from Localstack.
Hope this helps and solves your issue.
Please don't hesitate to reach out with further questions.

**Comment by kbret1** [comment]
@lakkeger We added skip_requesting_account_id in Terraform 1.6 because we ran into this error below.   After seeing your comment the  skip_requesting_account_id = true is only required in the terraform_remote_state that is stored in S3 Bucket on LocalStack.   We removed it from the aws provider and the warning has gone away as you mentioned.

│ Error: Retrieving AWS account details: AWS account ID not previously found and failed retrieving via all available methods. See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for workaround and implications. Errors: 2 errors occurred:
│       * retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: ea67c804-0077-4b40-9431-53b25878769f, api error InvalidClientTokenId: The security token included in the request is invalid.
│       * retrieving account information via iam:ListRoles: operation error IAM: ListRoles, https response error StatusCode: 403, RequestID: 999362bf-512e-4538-b086-c159c9092cbf, api error InvalidClientTokenId: The security token included in the request is invalid.

**Comment by lakkeger** [comment]
Hi @kbret1,
Thank you for your patience. The above error message usually relates to wrong configuration of endpoints with the native terraform command. Seems like it's trying to connect to AWS instead of localstack. Can you verify please that you're using tflocal and not terraform please? Furthermore please include a complete trace log for your terraform run here if your error still persist with `TF_LOG=trace`.

**Comment by kbret1** [comment]
@lakkeger Your suggestion last month resolved the issue.  We had skip_requesting_account_id in the provider and in the terraform_remote_state.  Removing it from the provider resolved the issue.

This can be closed.  Thanks again!

**Comment by lakkeger** [comment]
@kbret1 Great, glad we could sort it out for you. Closing the issue then and please feel free to reach out if any questions or issues arises.
