### ISSUE TITLE
terraform backend s3 endpoints deprecated for endpoints.xyz

### ISSUE THREAD

**Issue by kbret1** [localstack/terraform-local#37]
We are using
Terraform version 1.6.2
terraform-local version 0.16.0
sts_enpoint, dynamodb_endpoint and iam_endpoint have been deprecated in  Terraform 1.6.

1.6 release notes: https://github.com/hashicorp/terraform/issues/30492
"Configuration settings related to overriding the locations of AWS service endpoints used by the provider now belong to a nested block endpoints. The top-level arguments dynamodb_endpoint, iam_endpoint, endpoint (fir S3), and sts_endpoint are now deprecated in favor of the nested equivalents."

Believe the https://github.com/localstack/terraform-local/blob/0b2d155e64afd128c3ecece159c0a45f1ed44d53/bin/tflocal#L60C1-L60C1
should be updated based upon the TF version.

│ Warning: Deprecated Parameter
│ 
│ The parameter "sts_endpoint" is deprecated. Use parameter "endpoints.sts" instead.
╵
╷
│ Warning: Deprecated Parameter
│ 
│ The parameter "dynamodb_endpoint" is deprecated. Use parameter "endpoints.dynamodb" instead.
╵
╷
│ Warning: Deprecated Parameter
│ 
│ The parameter "iam_endpoint" is deprecated. Use parameter "endpoints.iam" instead.
╵
╷
│ Warning: Deprecated Parameter
│ 
│ The parameter "endpoint" is deprecated. Use parameter "endpoints.s3" instead.

**Comment by lakkeger** [comment]
Hi @kbret1,
Thank you for taking the time to report this change. The team is planning to introduce this with the next version bump. We'll keep you updated.
