### ISSUE TITLE
Support OpenTofu

### ISSUE THREAD

**Issue by chenrui333** [localstack/terraform-local#38]
not sure if you want to do in this project or maybe create a new one as opentofu-local, but it would be nice to also support opentofu. Thanks!

**Comment by lakkeger** [comment]
Hi @chenrui333!
Thanks for reaching out.
We keep an eye on OT, but until it serves as a drop-in replacement of TF, you can use it the following way:
`TF_CMD=tofu tflocal init`
or aliasing it for something like `otlocal` the following way: `alias otlocal="TF_CMD=tofu tflocal"`
so you can use it without all the shebangs.
If you encounter any issues let us know so we'll can start to consider a separate wrapper if needed.
