### ISSUE TITLE
AWS dynamodb.DescribeContinuousBackups => 400 (UnknownOperationException)

### ISSUE THREAD

**Issue by futugyou** [localstack/terraform-local#4]
`resource "aws_dynamodb_table" "terraform_locks" {
  count        = length(var.stages)
  depends_on   = [aws_s3_bucket.terraform_state]
  name         = format("terraform_locks_%s", var.stages[count.index])
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }
}
`
Terraform v1.2.8
provider registry.terraform.io/hashicorp/aws v4.29.0

i user this tf file to create dynamodb table.
'tflocal apply -auto-approve' command executes normally, but this is an error in localstack log 'AWS dynamodb.DescribeContinuousBackups => 400 (UnknownOperationException)'.
and when i use 'awslocal dynamodb list-tables' command, and I did not find any tables.

**Comment by whummer** [comment]
Thanks for reporting @futugyou - looks like this particular API functionality is not yet implemented in DynamoDB LocalStack. Do you mind re-creating this issue in our issue tracker in the main repo here: https://github.com/localstack/localstack/issues . This will help us better prioritize it in our backlog.. Thanks for your help!

**Comment by futugyou** [comment]
> 

I think this issues I created in the wrong repo, you can close it and re-creating an isssue in main repo.

**Comment by whummer** [comment]
Ok thanks @futugyou - will close the issue. Just to confirm - you will create the ticket in the main repo, right? Thanks
