### ISSUE TITLE
tflocal --chdir fails

### ISSUE THREAD

**Issue by jordital** [localstack/terraform-local#48]
Using `terraform-local==0.17.1`

When running `tflocal -chdir=terraform init` or another terraform subcommand: plan, apply... The global flag `-chdir` is not honoured.

**Comment by lakkeger** [comment]
Hi @jordital,
Sorry to hear you have issues with the tool.
Could you share details about your environment please as I was unable to reproduce it locally? See my screenshot below.
<img width="636" alt="image" src="https://github.com/localstack/terraform-local/assets/43646571/98873470-6ba9-434b-9af1-579c70821e7f">

**Comment by lakkeger** [comment]
Since I'm unable to reproduce this issue and got no response in a long time I'm closing this issue.
