### ISSUE TITLE
s3 backend causes issue with terraform always thinking backend configuration has changed

### ISSUE THREAD

**Issue by paulrobello** [localstack/terraform-local#51]
When using tflocal version 1.18.0 with a s3 backend every time i run a terraform command i get
Error: Backend initialization required: please run "terraform init"
Reason: Backend configuration block has changed

running init completes without error but then the very next command has same error.

This issues does not happen with version 0.17.1

``` terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.20.0"
    }
  }
  backend "s3" {
    region  = "us-east-1"
    bucket  = "ls-iac-state-us-east-1"
    key     = "global-iac/project/lcl/terraform.tfstate"
    encrypt = true
  }
}
```

**Comment by paulrobello** [comment]
My backend is setup exactly as I pasted above, no endpoints.
I use this before issuing any other commands and this command succeeds but all others say backend changed.
``` bash
tflocal  init -upgrade -reconfigure
```

**Comment by lakkeger** [comment]
@paulrobello Can you please provide some information on your environment, as I'm unable to reproduce it? See screenshot below with your code applied on:
MacOS 14.4
Terraform 1.5.7 -> 1.7.4 (made a switch from old to new to reproduce the error)
tflocal 0.18.0
Localstack 3.2.0
![image](https://github.com/localstack/terraform-local/assets/43646571/f70ed800-9a5e-4294-aa8f-ef6d746e663f)

**Comment by paulrobello** [comment]
reproducer repo created [https://github.com/paulrobello/tflocal_s3_backend_bug](https://github.com/paulrobello/tflocal_s3_backend_bug)

**Comment by cabeaulac** [comment]
Reproducer failed for me. Digging into it.

**Comment by cabeaulac** [comment]
I see the apply worked. It's the call to `output` that's failing.

**Comment by cabeaulac** [comment]
Ok. I see there's a dependency problem.
If you pip install this `https://github.com/localstack-samples/multi-iac-devops/blob/main/devops-tooling/requirements.txt`
then the issue goes away.
@lakkeger

**Comment by cabeaulac** [comment]
Confirmed. terraform-local==0.17.1 `tflocal output` command works. terraform-local==0.18.0 does not. See screen shot. 

<img width="954" alt="Screenshot 2024-03-13 at 1 04 16 PM" src="https://github.com/localstack/terraform-local/assets/850718/0a332416-3e83-47a5-8cb8-a3002ec2d8cb">

**Comment by cabeaulac** [comment]
Seems this needs `output` also. 
https://github.com/localstack/terraform-local/pull/50/files#diff-cefcc5bf4701072dadd5e5562ed2158bc584429c4786694469981da508a869f7R39

**Comment by lakkeger** [comment]
This sample was useful @cabeaulac. Found the source of the error. I turned around the logic and I added an env variable to exclude a subcommand from proxying.
