### ISSUE TITLE
tflocal apply: argument named dashboard

### ISSUE THREAD

**Issue by Travis-Kirton** [localstack/terraform-local#9]
I have tried running the minimal example on the documentation (https://docs.localstack.cloud/user-guide/integrations/terraform/)

but I'm being thrown an error when running `tflocal apply`

the error is:
```
Error: Unsupported argument
│ 
│   on localstack_providers_override.tf line 27, in provider "aws":
│   27: dashboard = "http://localhost:4566"
│ 
│ An argument named "dashboard" is not expected here
```

I can see the file mentioned is created and then quickly removed during the apply. Am I running the right version?

Versions:
Terraform v1.3.7
on darwin_amd64
provider registry.terraform.io/hashicorp/aws v4.51.0

**Comment by whummer** [comment]
Thanks for reporting @Travis-Kirton . This could be related to an older version of the `localstack-client` package installed on your local machine. 

Can you please try upgrading these packages to the latest version, then try to `apply` again?
```
pip install --upgrade localstack-client terraform-local

```

**Comment by Travis-Kirton** [comment]
Yep, that was the issue! I appreciate the quick response :)
